# Generated by Django 5.2.17 on 2026-09-26 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_prohibited', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like_New'), ('good', 'Good'), ('fair', 'Fair')], max_length=20)),
                ('age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('defects', models.TextField(blank=True, max_length=2000)),
                ('accessories', models.TextField(blank=True, max_length=2000)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('open_to_offers', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('active', 'Active'), ('in_exchange', 'In exchange'), ('exchanged', 'Exchanged'), ('paused', 'Paused'), ('rejected', 'Rejected'), ('removed', 'Removed')], db_index=True, default='draft', max_length=25)),
                ('possession_verified', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=500)),
                ('public_id', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.itemlisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
