# Generated by Django 5.2.17 on 2026-09-26 12:53

import django.db.models.deletion
import exchanges.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('countered', 'Countered'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(default=exchanges.models.proposal_expiry)),
                ('offered_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers_sent', to='listings.itemlisting')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchanges.exchangeproposal')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_proposals', to=settings.AUTH_USER_MODEL)),
                ('requested_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers_received', to='listings.itemlisting')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('agreed', 'Agreed'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='agreed', max_length=20)),
                ('sender_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_details', models.TextField(blank=True, max_length=2000)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exchange', to='exchanges.exchangeproposal')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
