# Generated by Django 5.2.17 on 2026-09-26 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(default='NG', max_length=2)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('country', 'state', 'city'), name='unique_location')],
            },
        ),
    ]
